// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WarehouseManagement.Data;

#nullable disable

namespace WarehouseManagement.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("WarehouseManagement.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("WarehouseManagement.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("WarehouseManagement.Models.ExportReceipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CancelledByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("PostedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PostedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ReceiptNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0);

                    b.HasKey("Id");

                    b.HasIndex("CancelledByUserId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("PostedByUserId");

                    b.HasIndex("ReceiptNumber")
                        .IsUnique();

                    b.ToTable("ExportReceipts", t =>
                        {
                            t.HasCheckConstraint("CK_ExportReceipts_Status", "[Status] IN (0, 1, 2)");

                            t.HasCheckConstraint("CK_ExportReceipts_StatusAudit", "([Status] = 0 AND [PostedByUserId] IS NULL AND [PostedAt] IS NULL AND [CancelledByUserId] IS NULL AND [CancelledAt] IS NULL) OR ([Status] = 1 AND [PostedByUserId] IS NOT NULL AND [PostedAt] IS NOT NULL AND [CancelledByUserId] IS NULL AND [CancelledAt] IS NULL) OR ([Status] = 2 AND [CancelledByUserId] IS NOT NULL AND [CancelledAt] IS NOT NULL AND (([PostedByUserId] IS NULL AND [PostedAt] IS NULL) OR ([PostedByUserId] IS NOT NULL AND [PostedAt] IS NOT NULL)))");
                        });
                });

            modelBuilder.Entity("WarehouseManagement.Models.ExportReceiptDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExportReceiptId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal?>("UnitCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ExportReceiptId", "ProductId")
                        .IsUnique();

                    b.ToTable("ExportReceiptDetails", t =>
                        {
                            t.HasCheckConstraint("CK_ExportReceiptDetails_Quantity_Positive", "[Quantity] > 0");

                            t.HasCheckConstraint("CK_ExportReceiptDetails_UnitCost_NonNegative", "[UnitCost] IS NULL OR [UnitCost] >= 0");
                        });
                });

            modelBuilder.Entity("WarehouseManagement.Models.ImportReceipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CancelledByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("PostedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PostedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ReceiptDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("CONVERT(date, GETDATE())");

                    b.Property<string>("ReceiptNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0);

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CancelledByUserId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("PostedByUserId");

                    b.HasIndex("ReceiptNumber")
                        .IsUnique();

                    b.HasIndex("SupplierId");

                    b.ToTable("ImportReceipts", t =>
                        {
                            t.HasCheckConstraint("CK_ImportReceipts_Status", "[Status] IN (0, 1, 2)");

                            t.HasCheckConstraint("CK_ImportReceipts_StatusAudit", "([Status] = 0 AND [PostedByUserId] IS NULL AND [PostedAt] IS NULL AND [CancelledByUserId] IS NULL AND [CancelledAt] IS NULL) OR ([Status] = 1 AND [PostedByUserId] IS NOT NULL AND [PostedAt] IS NOT NULL AND [CancelledByUserId] IS NULL AND [CancelledAt] IS NULL) OR ([Status] = 2 AND [CancelledByUserId] IS NOT NULL AND [CancelledAt] IS NOT NULL AND (([PostedByUserId] IS NULL AND [PostedAt] IS NULL) OR ([PostedByUserId] IS NOT NULL AND [PostedAt] IS NOT NULL)))");
                        });
                });

            modelBuilder.Entity("WarehouseManagement.Models.ImportReceiptDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ImportReceiptId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("UnitCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ImportReceiptId", "ProductId")
                        .IsUnique();

                    b.ToTable("ImportReceiptDetails", t =>
                        {
                            t.HasCheckConstraint("CK_ImportReceiptDetails_Quantity_Positive", "[Quantity] > 0");

                            t.HasCheckConstraint("CK_ImportReceiptDetails_UnitCost_NonNegative", "[UnitCost] >= 0");
                        });
                });

            modelBuilder.Entity("WarehouseManagement.Models.InventoryTransaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("BalanceAfter")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("BalanceBefore")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<int?>("ExportReceiptId")
                        .HasColumnType("int");

                    b.Property<int?>("ImportReceiptId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("OccurredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("PerformedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("QuantityChange")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<long?>("ReversedTransactionId")
                        .HasColumnType("bigint");

                    b.Property<byte>("TransactionType")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("ExportReceiptId");

                    b.HasIndex("ImportReceiptId");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("PerformedByUserId");

                    b.HasIndex("ProductId")
                        .IsUnique()
                        .HasDatabaseName("UX_InventoryTransactions_Product_OpeningBalance")
                        .HasFilter("[TransactionType] = 6");

                    b.HasIndex("ReversedTransactionId")
                        .IsUnique()
                        .HasFilter("[ReversedTransactionId] IS NOT NULL");

                    b.HasIndex("TransactionType");

                    b.HasIndex("ProductId", "OccurredAt");

                    b.HasIndex("ExportReceiptId", "ProductId", "TransactionType")
                        .IsUnique()
                        .HasFilter("[ExportReceiptId] IS NOT NULL");

                    b.HasIndex("ImportReceiptId", "ProductId", "TransactionType")
                        .IsUnique()
                        .HasFilter("[ImportReceiptId] IS NOT NULL");

                    b.ToTable("InventoryTransactions", t =>
                        {
                            t.HasCheckConstraint("CK_InventoryTransactions_BalanceEquation", "[BalanceAfter] = [BalanceBefore] + [QuantityChange]");

                            t.HasCheckConstraint("CK_InventoryTransactions_Balances_NonNegative", "[BalanceBefore] >= 0 AND [BalanceAfter] >= 0");

                            t.HasCheckConstraint("CK_InventoryTransactions_NoSelfReversal", "[ReversedTransactionId] IS NULL OR [ReversedTransactionId] <> [Id]");

                            t.HasCheckConstraint("CK_InventoryTransactions_QuantityChange_NonZero", "[QuantityChange] <> 0");

                            t.HasCheckConstraint("CK_InventoryTransactions_QuantityDirection", "([TransactionType] IN (0, 3, 4, 6) AND [QuantityChange] > 0) OR ([TransactionType] IN (1, 2, 5) AND [QuantityChange] < 0)");

                            t.HasCheckConstraint("CK_InventoryTransactions_ReversalReference", "([TransactionType] IN (2, 3) AND [ReversedTransactionId] IS NOT NULL) OR ([TransactionType] NOT IN (2, 3) AND [ReversedTransactionId] IS NULL)");

                            t.HasCheckConstraint("CK_InventoryTransactions_Source", "([TransactionType] IN (0, 2) AND [ImportReceiptId] IS NOT NULL AND [ExportReceiptId] IS NULL) OR ([TransactionType] IN (1, 3) AND [ImportReceiptId] IS NULL AND [ExportReceiptId] IS NOT NULL) OR ([TransactionType] IN (4, 5, 6) AND [ImportReceiptId] IS NULL AND [ExportReceiptId] IS NULL)");

                            t.HasCheckConstraint("CK_InventoryTransactions_Type", "[TransactionType] IN (0, 1, 2, 3, 4, 5, 6)");
                        });
                });

            modelBuilder.Entity("WarehouseManagement.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AverageUnitCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<decimal>("CurrentQuantity")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal>("MinimumStockLevel")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Products", t =>
                        {
                            t.HasCheckConstraint("CK_Products_AverageUnitCost_NonNegative", "[AverageUnitCost] IS NULL OR [AverageUnitCost] >= 0");

                            t.HasCheckConstraint("CK_Products_CurrentQuantity_NonNegative", "[CurrentQuantity] >= 0");

                            t.HasCheckConstraint("CK_Products_MinimumStockLevel_NonNegative", "[MinimumStockLevel] >= 0");
                        });
                });

            modelBuilder.Entity("WarehouseManagement.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("WarehouseManagement.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("WarehouseManagement.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarehouseManagement.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("WarehouseManagement.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WarehouseManagement.Models.ExportReceipt", b =>
                {
                    b.HasOne("WarehouseManagement.Models.ApplicationUser", "CancelledByUser")
                        .WithMany("CancelledExportReceipts")
                        .HasForeignKey("CancelledByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("WarehouseManagement.Models.ApplicationUser", "CreatedByUser")
                        .WithMany("CreatedExportReceipts")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WarehouseManagement.Models.ApplicationUser", "PostedByUser")
                        .WithMany("PostedExportReceipts")
                        .HasForeignKey("PostedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CancelledByUser");

                    b.Navigation("CreatedByUser");

                    b.Navigation("PostedByUser");
                });

            modelBuilder.Entity("WarehouseManagement.Models.ExportReceiptDetail", b =>
                {
                    b.HasOne("WarehouseManagement.Models.ExportReceipt", "ExportReceipt")
                        .WithMany("Details")
                        .HasForeignKey("ExportReceiptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WarehouseManagement.Models.Product", "Product")
                        .WithMany("ExportReceiptDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExportReceipt");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WarehouseManagement.Models.ImportReceipt", b =>
                {
                    b.HasOne("WarehouseManagement.Models.ApplicationUser", "CancelledByUser")
                        .WithMany("CancelledImportReceipts")
                        .HasForeignKey("CancelledByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("WarehouseManagement.Models.ApplicationUser", "CreatedByUser")
                        .WithMany("CreatedImportReceipts")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WarehouseManagement.Models.ApplicationUser", "PostedByUser")
                        .WithMany("PostedImportReceipts")
                        .HasForeignKey("PostedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("WarehouseManagement.Models.Supplier", "Supplier")
                        .WithMany("ImportReceipts")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CancelledByUser");

                    b.Navigation("CreatedByUser");

                    b.Navigation("PostedByUser");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("WarehouseManagement.Models.ImportReceiptDetail", b =>
                {
                    b.HasOne("WarehouseManagement.Models.ImportReceipt", "ImportReceipt")
                        .WithMany("Details")
                        .HasForeignKey("ImportReceiptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WarehouseManagement.Models.Product", "Product")
                        .WithMany("ImportReceiptDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ImportReceipt");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WarehouseManagement.Models.InventoryTransaction", b =>
                {
                    b.HasOne("WarehouseManagement.Models.ExportReceipt", "ExportReceipt")
                        .WithMany("InventoryTransactions")
                        .HasForeignKey("ExportReceiptId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("WarehouseManagement.Models.ImportReceipt", "ImportReceipt")
                        .WithMany("InventoryTransactions")
                        .HasForeignKey("ImportReceiptId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("WarehouseManagement.Models.ApplicationUser", "PerformedByUser")
                        .WithMany("PerformedInventoryTransactions")
                        .HasForeignKey("PerformedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WarehouseManagement.Models.Product", "Product")
                        .WithMany("InventoryTransactions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WarehouseManagement.Models.InventoryTransaction", "ReversedTransaction")
                        .WithOne("ReversalTransaction")
                        .HasForeignKey("WarehouseManagement.Models.InventoryTransaction", "ReversedTransactionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ExportReceipt");

                    b.Navigation("ImportReceipt");

                    b.Navigation("PerformedByUser");

                    b.Navigation("Product");

                    b.Navigation("ReversedTransaction");
                });

            modelBuilder.Entity("WarehouseManagement.Models.Product", b =>
                {
                    b.HasOne("WarehouseManagement.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WarehouseManagement.Models.ApplicationUser", b =>
                {
                    b.Navigation("CancelledExportReceipts");

                    b.Navigation("CancelledImportReceipts");

                    b.Navigation("CreatedExportReceipts");

                    b.Navigation("CreatedImportReceipts");

                    b.Navigation("PerformedInventoryTransactions");

                    b.Navigation("PostedExportReceipts");

                    b.Navigation("PostedImportReceipts");
                });

            modelBuilder.Entity("WarehouseManagement.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("WarehouseManagement.Models.ExportReceipt", b =>
                {
                    b.Navigation("Details");

                    b.Navigation("InventoryTransactions");
                });

            modelBuilder.Entity("WarehouseManagement.Models.ImportReceipt", b =>
                {
                    b.Navigation("Details");

                    b.Navigation("InventoryTransactions");
                });

            modelBuilder.Entity("WarehouseManagement.Models.InventoryTransaction", b =>
                {
                    b.Navigation("ReversalTransaction");
                });

            modelBuilder.Entity("WarehouseManagement.Models.Product", b =>
                {
                    b.Navigation("ExportReceiptDetails");

                    b.Navigation("ImportReceiptDetails");

                    b.Navigation("InventoryTransactions");
                });

            modelBuilder.Entity("WarehouseManagement.Models.Supplier", b =>
                {
                    b.Navigation("ImportReceipts");
                });
#pragma warning restore 612, 618
        }
    }
}
